#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
polybar -r main &
keepassxc &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           5
bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          32
bspc config focus_follows_pointer true

bspc rule -r "*"
bspc rule -a KeePassXC state=floating center=on hidden=on sticky=on
